const D=window.SHioriData;
const EXTRA={
  budgets:[
    ["Day 1 – Arrival + N'EX","¥30,000","N'EX round-trip + dinner/snacks + local arrival expenses"],
    ["Day 2 – Kamakura + Enoshima","¥45,000","Transport + Enoden + Romancecar + attractions + meals"],
    ["Day 3 – Lutia + Nakano + Shibuya","¥155,000","Hair + shopping + fashion + Donki"],
    ["Day 4 – Kokubunji + MAPPA + Ginza","¥133,000","Local morning + MAPPA + knife + tea + Bar Lupin"],
    ["Day 5 – Yokohama","¥40,000","BSD museum + food + Animate + transport"],
    ["Day 6 – Gotokuji + Minka-en + SPY","¥150,000","Includes ¥80k keyboard reserve; SPY tickets already paid"],
    ["Day 7 – Sayama + Koganei + Kichijoji","¥25,000","Tea experience + transport + food + small shopping"],
    ["Day 8 – Departure","¥21,000","Airport food + souvenirs + contingency"],
    ["Cebu Pacific additional baggage","¥7,500","Separate reserve"],
    ["2 perfumes reserve","¥16,000","2 primaniacs perfumes"],
    ["Martin shoes reserve — 3 pairs","¥70,000","Separate shoe reserve"],
    ["TOTAL TRIP BUDGET","¥692,500","≈ ₱277,000"]
  ],
  packing:{
    Cha:["Documents for IO","Powerbank","Toiletries","Makeup","Charger","Hair Straightener","AirPods","Wallet","Jacket","Tops","Dress","Bottoms","Scarf","Boots","Shoes","Slippers","Underwear","Bra","Socks","Safety Shorts","Perfume","Hat","Hair accessories","Accessories","Napkin","Panty Liner","Wet Wipes","Alcohol","Glasses","Contact Lens","Dear Face","Toothpick","GOJO LOOK UP"],
    Martin:["Documents for IO","Powerbank","Toiletries","Charger","Earphones","Wallet","Jacket","Tops","Bottoms","Shoes","Slippers","Underwear","Socks","Accessories","Alcohol","Wet Wipes","Glasses","Contact Lens","Scarf","Toothpick"],
    Both:["Adapter JP plug","Phone stand","Scale for bag","Vacuum air pump","Medicine","Mini Trash Bag","Facemask"]
  },
  requirements:{
    "Visa / application":["Visa form — TO PRINT","Passport","Bank cert","Marriage cert — TO RECEIVE","COE — TO PRINT","BIR — TO PRINT","Authorization Letter — TO PRINT","Multiple Entry — TO PRINT","PRC ID Martin","Picture","Payslip — TO PRINT","Cover letter — TO PRINT","Approved leave of absence"],
    "Immigration / travel":["Passport w/ visa","Boarding Pass","Return Ticket","Hotel accommodation","Itinerary","Travel Insurance","Marriage Cert","COE","Company ID","3 months payslip","Approved Leaves","Bank Statement","Bookings of activities"]
  },
  inbox:["Dr. Stone exhibition","Hitachi Seaside Park","JJK exhibition","Tochio-age (Takadanobaba honten)","Camera store","Computer/keyboard store in Takadanobaba","Animate","Okutama day trip","Nikko autumn day trip","Okashi no Machioka — Shinjuku","Niki no Kashi — Ueno / Ameyoko","Takeya — Okachimachi / Ueno"]
};
let state={view:"days",day:2,pack:"Cha"};
const saved=JSON.parse(localStorage.getItem("shioriState")||"{}");
const done=saved.done||{},packDone=saved.packDone||{},notes=saved.notes||{};
function save(){localStorage.setItem("shioriState",JSON.stringify({done,packDone,notes}))}
const labels={days:"Itinerary",trip:"Trip",transport:"Transport",reservations:"Bookings",budget:"Budget",packing:"Packing",docs:"IO Docs"};
function topbar(){return `<div class="topbar"><div class="brand"><div class="brand-title">Shiori<small>OCT 18–25, 2026</small></div><div class="trip-chip">Japan<br>October 2026</div></div><div class="nav">${Object.entries(labels).map(([v,l])=>`<button data-view="${v}" class="${state.view===v?'active':''}">${l}</button>`).join('')}</div></div>`}
function bottom(){const items=[["days","🗓️","Days"],["trip","♡","Trip"],["transport","🚆","Transit"],["reservations","🎟️","Book"],["budget","¥","Budget"],["packing","🧳","Pack"]];return `<div class="bottom-nav" style="grid-template-columns:repeat(6,1fr)">${items.map(([v,i,l])=>`<button data-view="${v}" class="${state.view===v?'active':''}"><span class="icon">${i}</span>${l}</button>`).join('')}</div>`}
function hero(label,title,jp,date){return `<section class="hero"><div class="hero-grid"><div class="day-badge"><div class="day">${label}</div><div class="date">${date||''}</div></div><div class="hero-copy"><h1>${title}</h1>${jp?`<div class="jp">${jp}</div>`:''}</div></div></section>`}
function dayView(){const d=D.days.find(x=>x.day===state.day);return `<main><div class="day-switch">${D.days.map(x=>`<button data-day="${x.day}" class="${x.day===d.day?'active':''}">Day ${x.day}</button>`).join('')}</div>${hero('Day '+d.day,d.title,d.jp,d.date)}<div class="layout"><section class="card"><div class="timeline-head"><div>Time</div><div>✓</div><div>Plan / Activity</div><div>Location</div><div>Notes</div></div>${d.timeline.map((x,i)=>{const k=`d${d.day}-${i}`,on=!!done[k];return `<div class="timeline-row ${on?'done':''}"><div class="time">${x[0]}</div><div class="check-wrap"><button data-tick="${k}" class="check-btn ${on?'on':''}">${on?'✓':''}</button></div><div class="activity">${x[1]} ${x[2]}</div><div class="location">📍 ${x[3]}</div><div class="note">${x[4]}</div></div>`}).join('')}</section><aside><section class="card" style="margin-bottom:14px"><div class="card-title">☀️ Day Overview</div><div class="card-body">${d.overview}</div></section><section class="card" style="margin-bottom:14px"><div class="card-title">⭐ Priority</div><div class="card-body">${d.priorities.map(x=>`<div class="priority-line">✅ ${x}</div>`).join('')}${d.optional.map(x=>`<div class="priority-line">☐ ${x}</div>`).join('')}</div></section><section class="card" style="margin-bottom:14px"><div class="card-title">¥ Budget Estimate</div><div class="card-body"><div class="kv"><span>Safe day allocation</span><b>${d.budget}</b></div><div class="kv"><span>Start</span><b>${d.start}</b></div><div class="kv"><span>End</span><b>${d.end}</b></div></div></section><section class="card notes"><div class="card-title">✎ My Notes</div><div class="card-body"><textarea data-note="${d.day}" placeholder="Anything to remember on this day…">${notes[d.day]||''}</textarea></div></section></aside></div></main>`}
function tripView(){return `<main>${hero('8 Days','Japan October Trip','旅のしおり','Oct 18–25')}<div class="summary-grid"><div class="mini"><small>Trip cap</small><strong>${D.trip.budget}</strong></div><div class="mini"><small>Cash</small><strong>${D.trip.cash}</strong></div><div class="mini"><small>Suica</small><strong>${D.trip.suica}</strong></div><div class="mini"><small>Hotel</small><strong style="font-size:16px">${D.trip.hotel}</strong></div></div><br><section class="card" style="margin-bottom:14px"><div class="card-title">♡ Trip at a glance</div>${D.days.map(d=>`<div class="list-row"><b>Day ${d.day} • ${d.date}</b>${d.title}<div class="section-note">${d.subtitle}</div><div class="pill-row" style="margin-top:7px"><span class="pill">${d.budget}</span><span class="pill pink">${d.start} → ${d.end}</span></div></div>`).join('')}</section><section class="card"><div class="card-title">📝 Planning Inbox / To Add</div><div class="card-body"><div class="pill-row">${EXTRA.inbox.map(x=>`<span class="pill pink">${x}</span>`).join('')}</div></div></section></main>`}
function transportView(){return `<main>${hero('Transit','Transportation Guide','移動ガイド','Days 1–8')}${D.days.map(d=>`<section class="card transport-day"><div class="card-title">Day ${d.day} • ${d.title}</div>${(D.transport[d.day]||[]).map(t=>`<div class="transport-item">${t}</div>`).join('')}</section>`).join('')}</main>`}
function reservationsView(){return `<main>${hero('Book','Bookings & Tickets','予約・チケット','Status tracker')}<section class="card">${D.reservations.map(r=>`<div class="list-row"><b>${r[0]}</b><div>${r[1]}</div><div class="status">${r[2]}</div></div>`).join('')}</section></main>`}
function budgetView(){return `<main>${hero('¥','Trip Budget','旅費','Conservative caps')}<div class="summary-grid"><div class="mini"><small>Total conservative cap</small><strong>${D.trip.budget}</strong></div><div class="mini"><small>Cash withdrawal</small><strong>${D.trip.cash}</strong></div></div><br><section class="card">${EXTRA.budgets.map(r=>`<div class="list-row"><div class="kv"><span><b>${r[0]}</b><span class="section-note">${r[2]}</span></span><b>${r[1]}</b></div></div>`).join('')}</section></main>`}
function packingView(){const a=EXTRA.packing[state.pack];return `<main>${hero('Pack','Packing Checklist','持ち物','Saved on this phone')}<div class="day-switch">${Object.keys(EXTRA.packing).map(x=>`<button data-pack="${x}" class="${x===state.pack?'active':''}">${x}</button>`).join('')}</div><section class="card">${a.map((x,i)=>{const k=`${state.pack}-${i}`,on=!!packDone[k];return `<div class="list-row ${on?'done':''}" style="display:flex;gap:10px;align-items:center;${on?'opacity:.5;text-decoration:line-through':''}"><button class="check-btn ${on?'on':''}" data-packtick="${k}">${on?'✓':''}</button><b style="margin:0">${x}</b></div>`}).join('')}</section></main>`}
function docsView(){return `<main>${hero('IO','Documents & Requirements','必要書類','Visa + immigration')}${Object.entries(EXTRA.requirements).map(([k,a])=>`<section class="card" style="margin-bottom:14px"><div class="card-title">${k}</div>${a.map(x=>`<div class="list-row">${x}</div>`).join('')}</section>`).join('')}</main>`}
function render(){const fn={days:dayView,trip:tripView,transport:transportView,reservations:reservationsView,budget:budgetView,packing:packingView,docs:docsView}[state.view];document.getElementById('app').innerHTML=topbar()+fn()+bottom();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();scrollTo(0,0)});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=+b.dataset.day;state.view='days';render();scrollTo(0,0)});document.querySelectorAll('[data-tick]').forEach(b=>b.onclick=()=>{done[b.dataset.tick]=!done[b.dataset.tick];save();render()});document.querySelectorAll('[data-note]').forEach(t=>t.oninput=()=>{notes[t.dataset.note]=t.value;save()});document.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>{state.pack=b.dataset.pack;render()});document.querySelectorAll('[data-packtick]').forEach(b=>b.onclick=()=>{packDone[b.dataset.packtick]=!packDone[b.dataset.packtick];save();render()})}
render();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');