const D=window.SHioriData;
const EXTRA={
  budgets:[["Day 1 – Arrival + N'EX","¥30,000"],["Day 2 – Kamakura + Enoshima","¥45,000"],["Day 3 – Lutia + Nakano + Shibuya","¥155,000"],["Day 4 – Kokubunji + MAPPA + Ginza","¥133,000"],["Day 5 – Yokohama","¥40,000"],["Day 6 – Gotokuji + Minka-en + SPY","¥150,000"],["Day 7 – Sayama + Koganei + Kichijoji","¥25,000"],["Day 8 – Departure","¥21,000"],["Additional baggage","¥7,500"],["2 perfumes reserve","¥16,000"],["Martin shoes reserve","¥70,000"],["TOTAL","¥692,500"]],
  packing:{Cha:["Documents for IO","Powerbank","Toiletries","Makeup","Charger","Hair Straightener","AirPods","Wallet","Jacket","Tops","Dress","Bottoms","Scarf","Boots","Shoes","Slippers","Underwear","Bra","Socks","Safety Shorts","Perfume","Hat","Hair accessories","Accessories","Napkin","Panty Liner","Wet Wipes","Alcohol","Glasses","Contact Lens","Dear Face","Toothpick","GOJO LOOK UP"],Martin:["Documents for IO","Powerbank","Toiletries","Charger","Earphones","Wallet","Jacket","Tops","Bottoms","Shoes","Slippers","Underwear","Socks","Accessories","Alcohol","Wet Wipes","Glasses","Contact Lens","Scarf","Toothpick"],Both:["Adapter JP plug","Phone stand","Scale for bag","Vacuum air pump","Medicine","Mini Trash Bag","Facemask"]},
  requirements:{"Visa / application":["Visa form — TO PRINT","Passport","Bank cert","Marriage cert — TO RECEIVE","COE — TO PRINT","BIR — TO PRINT","Authorization Letter — TO PRINT","Multiple Entry — TO PRINT","PRC ID Martin","Picture","Payslip — TO PRINT","Cover letter — TO PRINT","Approved leave of absence"],"Immigration / travel":["Passport w/ visa","Boarding Pass","Return Ticket","Hotel accommodation","Itinerary","Travel Insurance","Marriage Cert","COE","Company ID","3 months payslip","Approved Leaves","Bank Statement","Bookings of activities"]}
};

const SUMMARY={
  meta:[
    ["Hotel","Hananosato Takadanobaba, 4-12-7 Takadanobaba, Shinjuku-ku"],["Trip cap","¥692,500 couple ≈ ₱277,000"],["Cash plan","¥88,000 withdrawal + ¥15,000 Suica each"],["N’EX","Round Trip ticket for Oct 18 + Oct 25"],
    ["Arrival","Oct 18 • ILO 07:50 → MNL T2 09:10 → MNL T3 12:15 → NRT T2 18:00"],["Departure","Oct 25 • NRT T2 12:50 → MNL T3 17:30 → MNL T2 21:50 → ILO 23:15"],["Separate reserves","Baggage ¥7,500 • Perfumes ¥16,000 • Shoes ¥70,000"],["Planning rate","¥1 ≈ ₱0.40"]
  ],
  days:[
    ["Oct 18 Sun","Day 1 • Flight + Arrival","ILO → MNL → Narita T2 → Shinjuku → Takadanobaba • self-check-in • light dinner/groceries","5J 448 07:50–09:10 • 5J 5056 12:15–18:00 • ⭐ N’EX 50 preferred","07:50 flight","~22:00 hotel if N’EX 50","¥30,000","NRT T2 arrival 18:00 • N’EX 50: T2・3 19:53 → Shinjuku 21:18","If not fully ready in the JR station area by ~19:30–19:35, use N’EX 52 at 20:47 instead of rushing."],
    ["Oct 19 Mon","Day 2 • Kamakura + Enoshima","Renbai • Great Buddha • Goryo/Joju-in/Gokurakuji • Inamuragasaki • Koshigoe • Enoshima Iwaya • sunset","Great Buddha protected • sunset ~17:03","05:45","~21:45 hotel","¥45,000","Takadanobaba → Shinagawa → Kamakura • ⭐ 19:39 Romancecar Enoshima No. 6 → Shinjuku 20:48 if reserved","Cut Inamuragasaki time / optional Shonan Candle first if behind"],
    ["Oct 20 Tue","Day 3 • Shinjuku + Nakano + Shibuya","Yamato ticket pickup • Can★Do Nishi-Shinjuku • Lutia • optional 100-yen buffer • Nakano Broadway • Shibuya MODI BSD × h.NAOTO + Onitsuka • SHIBUYA109 ≥2h • MEGA Donki","Lutia 11:00–13:30 ✅ booked • BSD × h.NAOTO at Shibuya MODI before 20:00","07:35","~00:10 hotel","¥155,000","JR local day • ⭐ Shinjuku→Nakano 14:28 • ⭐ Nakano 16:37 local→Shinjuku→Shibuya","Protect morning 100-yen shopping, Nakano, MODI, and SHIBUYA109."],
    ["Oct 21 Wed","Day 4 • Kokubunji + MAPPA + Ginza","Tonogayato Garden • Otaka-no-Michi springs • Musashi Kokubunji • Hōnenya soba • MAPPA • CHA Ginza • Kiya • Bar Lupin","MAPPA target 15:30 • arrival buffer from ~14:45","~08:00 leave hotel","~21:15–21:30 hotel","¥133,000","Yamanote→Shinjuku • ⭐ ~08:14 Chuo Rapid→Kokubunji • ⭐ ~12:53 Chuo eastbound→Tokyo/Yurakucho","Protect Tonogayato 09:00 opening + Kokubunji lunch."],
    ["Oct 22 Thu","Day 5 • Yokohama BSD","Yamate • Diplomat House • France-yama • BSD museum • Motomachi • Chinatown • Yamashita • Osanbashi • Red Brick • night views • Noge • Animate","BSD museum 11:00–12:10 • sunset 16:58 • Animate closes 21:00","~07:03 train target","~22:15 hotel","¥40,000","Takadanobaba→Shinagawa→Ishikawacho • ⭐ Yokohama 21:26→Shinjuku return","Protect museum + sunset/blue hour + Animate."],
    ["Oct 23 Fri","Day 6 • Gotokuji + Minka-en + Unagi + Ikebukuro + SPY","Gotokuji • Nihon Minka-en • Manmaru Honten unagi • Ikebukuro keyboard stores • SPY×FAMILY 2 musical • optional post-show keyboard return","SPY musical 17:45 ✅ paid • Manmaru ~13:30 • keyboards ~14:20–16:20 PROTECTED","~07:00","~23:00 hotel","¥150,000","⭐ 07:21 Odakyu LOCAL • ⭐ 09:32 Local • ⭐ 12:38 Express → Shinjuku → Ikebukuro","Reserve Manmaru if possible; keyboards BEFORE show remain primary."],
    ["Oct 24 Sat","Day 7 • Sayama + Koganei + Kichijoji + Kagurazaka","Miyanoen tea picking • Edo-Tokyo Open Air Museum + Tokyo Grand Tea Ceremony atmosphere • Kichijoji • Harmonica Yokocho • Kagurazaka","Miyanoen 10:00 reservation target • museum closes 16:30 • admission FREE Oct 24","~06:50","~21:45–22:00 hotel","¥25,000","⭐ 07:13 Seibu→Sayamashi 07:59 • ⭐ 08:22 bus • direct Chuo-Sobu to Iidabashi","Do not shorten Miyanoen for one bus. Shorten Kagurazaka first if tired."],
    ["Oct 25 Sun","Day 8 • Departure + Flight Home","Checkout • Takadanobaba → Shinjuku • N’EX → Narita T2 • primaniacs • T2 airside Fa-So-La AKIHABARA • 5J 5055 → Manila T3 • 5J 2269 → Iloilo","⭐ N’EX 7 07:27→08:58 • primaniacs ~09:05–09:25 • 5J 5055 12:50 • 5J 2269 21:50","06:35 leave hotel","23:15 arrive Iloilo","¥21,000","⭐ Yamanote ~06:43 • N’EX 7 preferred • Manila connection currently planned in T3 under current 5J policy","Confirm final terminal and baggage/connection procedure before travel."]
  ],
  budget:[["Daily itinerary caps","¥599,000","≈ ₱239,600","Days 1–8 combined"],["Cebu Pacific baggage reserve","¥7,500","≈ ₱3,000",""],["2 perfumes reserve","¥16,000","≈ ₱6,400",""],["Martin shoes reserve — 3 pairs","¥70,000","≈ ₱28,000",""],["TOTAL CONSERVATIVE TRIP CAP","¥692,500","≈ ₱277,000","Suica preload is cash-flow, not double-counted"]]
};

const SCHEDULE={
  1:[["07:45","✈️ 07:50 5J 448 — Iloilo → Manila T2 • arrive 09:10"],["09:15","🛬 Manila T2 • 3h05 layover • transfer to T3"],["12:15","✈️ 12:15 5J 5056 — Manila T3 → Narita T2"],["18:00","🛬 Arrive Narita T2 • immigration + baggage"],["19:00","💴 Cash withdrawal • Suica • eSIM/setup"],["19:30","⭐ N’EX decision point"],["19:45","🚆 ⭐ N’EX 50 — T2・3 19:53 → Shinjuku 21:18"],["21:15","🚉 Shinjuku → Takadanobaba"],["21:45","🏠 Hananosato self-check-in"],["22:00","🍱 Light dinner + groceries"]],
  2:[["05:45","🚆 Leave Hananosato → Shinagawa → Kamakura"],["06:00","⭐ 06:04 Yamanote → Shinagawa • ⭐ 06:41 Yokosuka → Kamakura"],["07:30","🥬 Kamakura Renbai Market"],["08:15","🚋 ⭐ 08:24 Enoden Kamakura → Hase"],["08:45","🗿 Great Buddha / Kotoku-in"],["09:15","⛩️ Quiet Hase lanes • Goryo • Joju-in • Gokurakuji"],["11:00","🚋 ⭐ 11:05 Gokurakuji → Inamuragasaki"],["11:15","🌊 Inamuragasaki Park"],["11:30","🚋 ⭐ 11:39 → Koshigoe"],["12:00","🍣 Koshigoe seafood lunch • fishing port"],["13:30","⛩️ Walk to Enoshima • shrine/backstreets"],["15:30","🌊 Iwaya Caves → Chigogafuchi"],["16:45","🌅 Chigogafuchi sunset ~17:03"],["17:15","🕯️ Optional Shonan Candle"],["19:30","🚆 ⭐ 19:39 Romancecar Enoshima No. 6 → Shinjuku 20:48"],["21:00","🏠 Return to Takadanobaba"]],
  3:[["07:30","🚶 Leave hotel for Shinjuku"],["08:00","📦 Yamato — SPY ticket pickup if ready"],["09:00","🛍 Can★Do Nishi-Shinjuku — 100-yen"],["10:15","🚶 Can★Do → Lutia / salon buffer"],["10:45","💇 Arrive Lutia early"],["11:00","💇 Lutia Shinjuku — BOOKED 11:00–13:30"],["13:30","🍴 Light lunch"],["14:00","🛍 Optional 100-yen BUFFER only if needed"],["14:15","🚆 Move to JR Shinjuku • ⭐ 14:28 Chuo-Sobu target"],["14:30","🎌 Nakano Broadway"],["16:45","🚆 ⭐ 16:37 Nakano local → Shinjuku → Shibuya"],["17:15","🐯 Shibuya MODI — BSD × h.NAOTO + Onitsuka"],["18:30","🚶 MODI → SHIBUYA109"],["18:45","🛍️ SHIBUYA109 — PROTECTED"],["21:00","🍽️ Dinner"],["21:45","🛒 MEGA Don Quijote"],["23:45","🚆 ~23:55 Yamanote → Takadanobaba"]],
  4:[["08:00","🚆 Leave Hananosato → Shinjuku → Kokubunji • ⭐ ~08:14"],["08:45","🌿 Arrive Kokubunji / quiet pre-opening walk"],["09:00","🌳 Tonogayato Garden"],["10:00","🚶 Tonogayato → Otaka-no-Michi"],["10:30","💧 Otaka-no-Michi / spring area"],["11:15","⛩️ Musashi Kokubunji area / walk to Hōnenya"],["11:30","🍜 Hōnenya soba lunch"],["12:45","🚆 Kokubunji → Tokyo / Yurakucho • ⭐ ~12:53"],["13:30","☕ Yurakucho / Ginza flex + rest"],["14:45","🎟️ Move to MAPPA / entry buffer"],["15:30","🎟️ MAPPA EXPO — target 15:30"],["16:00","🎬 MAPPA EXPO — JJK priority"],["17:30","🚶 MAPPA → CHA・GINZA"],["17:45","🫖 CHA・GINZA"],["18:15","🔪 Kiya knife shopping"],["19:15","📚 Bar Lupin + light dinner"],["20:30","🚆 Return to Takadanobaba"],["21:15","🏠 Hananosato"]],
  5:[["07:00","🚆 Takadanobaba → Shinagawa → Ishikawacho"],["08:30","🏘️ Quiet Yamate walk"],["09:30","🏡 Italian Garden / Home of Diplomat"],["10:30","🌳 France-yama / Harbor View"],["11:00","📚 Sato Haruo exhibition × BSD"],["12:30","🛍️ Motomachi"],["13:00","🍴 Lunch"],["14:00","🥟 Chinatown"],["14:30","🌊 Yamashita Park"],["15:00","⚓ Osanbashi"],["16:15","🧱 Red Brick Warehouse"],["16:45","🌅 Yokohama sunset + blue hour — PRIORITY"],["18:15","🍽️ Noge dinner"],["20:00","🎌 Animate Yokohama VIVRE"],["21:15","🚆 ⭐ 21:26 Yokohama → Shinjuku"],["22:15","🏠 Hotel"]],
  6:[["06:30","☀️ Prep + breakfast"],["07:15","🚆 Takadanobaba → Shinjuku → Gotokuji • ⭐ 07:21 Odakyu Local"],["08:00","🐱 Gotokuji"],["09:15","🚆 Gotokuji → Mukogaoka-Yuen • ⭐ 09:32 Local"],["10:00","🏘️ Nihon Minka-en — PROTECTED 10:00–12:15"],["12:15","🚶 Leave Minka-en → Mukogaoka-yuen"],["12:30","🚆 Mukogaoka-Yuen → Shinjuku → Ikebukuro • ⭐ 12:38 Express"],["13:15","🍱 Manmaru Honten unagi • ~13:30"],["14:00","🚶 Manmaru → East Exit keyboard area"],["14:15","⌨️ BIC CAMERA Ikebukuro PC Store • PROTECTED"],["14:45","⌨️ Yodobashi comparison / backup"],["15:30","⌨️ Finalize / payment"],["16:00","🧳 Locker / snack / bathroom"],["16:30","🚶 Move toward Brillia HALL"],["17:45","🎟️ SPY×FAMILY 2 Musical — 17:45"],["20:30","🎭 SPY musical continues"],["21:00","🎭 Expected end ~20:55 / exit"],["21:15","⌨️ OPTIONAL keyboard-store return"],["21:45","🍽️ Dinner — Ikebukuro"],["22:30","🚆 Ikebukuro → Takadanobaba"],["23:00","🏠 Hotel ~23:00"]],
  7:[["06:30","☀️ Prep + breakfast"],["06:45","🚆 Leave for Sayamashi"],["07:15","🚆 ⭐ 07:13 Seibu → Sayamashi 07:59"],["08:15","🚌 ⭐ 08:22 Sayama 31 → Sayamadai-minami"],["09:15","🚶 Walk / arrive Miyanoen"],["10:00","🍵 Miyanoen tea-picking — reservation target"],["11:30","🛍️ Tea shop / walk back to bus"],["12:00","🚌 Return bus — 12:03 preferred / 12:22 backup"],["12:30","🚆 Sayamashi → Hana-Koganei"],["13:30","🍴 Quick lunch / museum transfer"],["14:00","🏘️ Edo-Tokyo Open Air Museum + Tokyo Grand Tea Ceremony atmosphere"],["16:30","🚆 Leave museum → Kichijoji"],["17:15","🏘️ Kichijoji / Sunroad / backstreets"],["18:30","🍽️ Harmonica Yokocho dinner"],["19:45","🚆 ~19:43 direct Chuo-Sobu → Iidabashi"],["20:15","🏮 Kagurazaka evening"],["21:30","🚇 Kagurazaka → Takadanobaba"],["22:00","🏠 Hotel / final packing"]],
  8:[["06:00","☀️ Wake + final prep"],["06:15","🧳 Checkout + light breakfast"],["06:45","🚆 ⭐ ~06:43 Yamanote → Shinjuku"],["07:15","🚆 ⭐ N’EX 7 — Shinjuku 07:27 → NRT T2・3 08:58"],["09:00","🛬 08:58 N’EX arrives NRT T2・3 → Terminal 2"],["09:15","🛍️ primaniacs T2 4F PRE-SECURITY"],["09:45","🛄 Check-in / bag drop / departure formalities"],["10:00","🛄 Immigration + security"],["10:15","🛍️ AIRSIDE Fa-So-La AKIHABARA / anime goods"],["10:45","🍱 Airside meal + shopping"],["11:30","🚶 Move toward gate"],["11:45","✈️ Gate / boarding buffer"],["12:45","✈️ 12:50 5J 5055 — Narita T2 → Manila T3"],["17:30","🛬 Manila T3 • 4h20 layover"],["21:45","✈️ 21:50 5J 2269 — Manila → Iloilo"],["23:15","🏠 Arrive Iloilo"]]
};

let state={view:'days',day:2,transitDay:7,scheduleDay:1,pack:'Cha'};
const saved=JSON.parse(localStorage.getItem('shioriState')||'{}');const done=saved.done||{},packDone=saved.packDone||{},notes=saved.notes||{};function save(){localStorage.setItem('shioriState',JSON.stringify({done,packDone,notes}))}
const labels={days:'Itinerary',summary:'Summary',schedule:'15-Min',transport:'Transport',reservations:'Bookings',budget:'Budget',packing:'Packing',docs:'IO Docs'};
function topbar(){return `<header class="topbar"><div class="brand"><div class="brand-title">Shiori<small>OCT 18–25, 2026</small></div><div class="trip-chip">Japan<br>October 2026</div></div><nav class="nav">${Object.entries(labels).map(([v,l])=>`<button data-view="${v}" class="${state.view===v?'active':''}">${l}</button>`).join('')}</nav></header>`}
function bottom(){const items=[["days","🗓️","Days"],["summary","♡","Summary"],["transport","🚆","Transit"],["reservations","🎟️","Book"],["budget","¥","Budget"]];return `<div class="bottom-nav">${items.map(([v,i,l])=>`<button data-view="${v}" class="${state.view===v?'active':''}"><span>${i}</span>${l}</button>`).join('')}</div>`}
function dayTabs(key='day'){return `<div class="day-switch">${D.days.map(x=>`<button data-${key}="${x.day}" class="${x.day===state[key]?'active':''}">Day ${x.day}</button>`).join('')}</div>`}
function banner(d,label=`Day ${d.day}`){return `<section class="sheet-banner"><div class="banner-day"><strong>${label}</strong><span>${d.date}</span></div><div class="banner-place"><h1>${d.title}</h1><div>${d.jp||''}</div></div></section>`}
function routeFor(d){const loc=[];d.timeline.forEach(x=>{const v=x[3];if(v&&!loc.includes(v))loc.push(v)});return loc.slice(0,9)}
function dayView(){const d=D.days.find(x=>x.day===state.day);const route=routeFor(d);return `<main>${dayTabs('day')}${banner(d)}<div class="sheet-layout"><section class="paper-card timetable"><div class="t-head"><div>Time</div><div>✓</div><div></div><div>Plan / Activity</div><div>Location</div><div>Notes</div></div>${d.timeline.map((x,i)=>{const k=`d${d.day}-${i}`,on=!!done[k];return `<div class="t-row ${on?'done':''}"><div class="time">${x[0]}</div><div class="check-wrap"><button data-tick="${k}" class="check-btn ${on?'on':''}">${on?'✓':''}</button></div><div class="emoji">${x[1]}</div><div class="activity">${x[2]}</div><div class="location">📍 ${x[3]}</div><div class="note">${x[4]}</div></div>`}).join('')}</section><aside class="side-stack"><section class="paper-card side mint"><h2>☀️ Day Overview</h2><p>${d.overview}</p></section><section class="paper-card side blush"><h2>⭐ Priority</h2>${d.priorities.map(x=>`<p>☑ ${x}</p>`).join('')}${d.optional.map(x=>`<p>☐ ${x}</p>`).join('')}</section><section class="paper-card side"><h2>¥ Budget Estimate</h2><div class="budget-line"><span>Day allocation</span><b>${d.budget}</b></div><div class="budget-line"><span>Start</span><b>${d.start}</b></div><div class="budget-line"><span>End</span><b>${d.end}</b></div></section><section class="paper-card side"><h2>✎ Notes</h2><textarea data-note="${d.day}" placeholder="Anything to remember…">${notes[d.day]||''}</textarea></section></aside></div><section class="paper-card route-card"><b>📍 Today’s Route</b><div class="route-line">${route.map((r,i)=>`<span>${r}</span>${i<route.length-1?'<i>→</i>':''}`).join('')}</div></section></main>`}

function splitTransit(s,i){const colon=s.indexOf(':');let route=colon>0?s.slice(0,colon).trim():`Transport option ${i+1}`;let details=colon>0?s.slice(colon+1).trim():s;let icon=/bus/i.test(s)?'🚌':/walk/i.test(s)?'🚶':/N’EX|N'EX/i.test(s)?'🚄':'🚆';let line=/bus/i.test(s)?'Bus':/N’EX|N'EX/i.test(s)?'JR Narita Express':'Train / rail';return {route,details,icon,line}}
function transportView(){const d=D.days.find(x=>x.day===state.transitDay),rows=(D.transport[d.day]||[]).map(splitTransit);return `<main>${dayTabs('transitDay')}${banner(d)}<section class="transport-title"><h1>Transportation Guide</h1><div>${d.title}</div></section><section class="paper-card transport-table"><div class="tr-head"><div>#</div><div>From → To</div><div>Mode</div><div>Transport / Line</div><div>Details</div><div>Notes</div></div>${rows.map((r,i)=>`<article class="tr-row"><div class="num">${String(i+1).padStart(2,'0')}</div><div class="fromto">${r.route}</div><div class="mode">${r.icon}</div><div class="line">${r.line}</div><div class="details">${r.details}</div><div class="tr-notes">⭐ = preferred option when shown. Recheck live platform / traffic conditions.</div></article>`).join('')}</section><div class="transit-bottom"><section class="paper-card quick"><h2>✓ Quick Notes</h2><p>Times are estimates. Use Suica where accepted. Starred departures are preferred; nearby departures are backups. Allow station navigation and transfer buffers.</p></section><section class="paper-card highlights"><h2>♥ Day ${d.day} Highlights</h2>${d.priorities.slice(0,4).map(x=>`<p>• ${x}</p>`).join('')}</section></div></main>`}

function summaryView(){const heads=['Date','Day / Area','Main Plan','Fixed / Timed Anchor','Start','Return / End','Safe Budget','Key Transport Anchor','Keep in Mind'];return `<main><section class="section-title"><h1>Trip Summary</h1><p class="section-sub">Cha + Martin • Hananosato Takadanobaba • mirrored from the Trip Summary sheet</p></section><section class="summary-meta">${SUMMARY.meta.map(([k,v])=>`<div class="mini"><small>${k}</small><strong>${v}</strong></div>`).join('')}</section><section class="paper-card summary-table"><div class="sum-head">${heads.map(h=>`<div>${h}</div>`).join('')}</div>${SUMMARY.days.map(r=>`<div class="sum-row">${r.map((v,i)=>`<div data-label="${heads[i]}">${v}</div>`).join('')}</div>`).join('')}</section><section class="paper-card budget-summary"><h2>💰 Trip Budget at a Glance</h2>${SUMMARY.budget.map(r=>`<div class="budget-summary-row"><b>${r[0]}</b><span>${r[1]}</span><span>${r[2]}</span><small>${r[3]}</small></div>`).join('')}</section></main>`}

function scheduleView(){const d=D.days.find(x=>x.day===state.scheduleDay),rows=SCHEDULE[d.day]||[];return `<main>${dayTabs('scheduleDay')}<section class="section-title"><h1>15-Min Schedule</h1><p class="section-sub">${d.date} • ${d.title}</p></section><section class="paper-card schedule-card"><div class="sched-head"><div>Time</div><div>Plan</div></div>${rows.map(r=>`<div class="sched-row"><time>${r[0]}</time><div>${r[1]}</div></div>`).join('')}</section><p class="schedule-note">This is the mobile companion view of the 15-Min Schedule sheet. Only populated time slots are shown so you do not have to scroll through empty intervals.</p></main>`}

function reservationsView(){return `<main><section class="section-title"><h1>Bookings & Tickets</h1></section><section class="paper-card list-card">${D.reservations.map(r=>`<div class="list-row"><b>${r[0]}</b><span>${r[1]}</span><em>${r[2]}</em></div>`).join('')}</section></main>`}
function budgetView(){return `<main><section class="section-title"><h1>Trip Budget</h1></section><section class="paper-card list-card">${EXTRA.budgets.map(r=>`<div class="list-row budget-line"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('')}</section></main>`}
function packingView(){const a=EXTRA.packing[state.pack];return `<main><section class="section-title"><h1>Packing Checklist</h1></section><div class="day-switch">${Object.keys(EXTRA.packing).map(x=>`<button data-pack="${x}" class="${x===state.pack?'active':''}">${x}</button>`).join('')}</div><section class="paper-card list-card">${a.map((x,i)=>{const k=`${state.pack}-${i}`,on=!!packDone[k];return `<div class="list-row pack-row ${on?'done':''}"><button class="check-btn ${on?'on':''}" data-packtick="${k}">${on?'✓':''}</button><b>${x}</b></div>`}).join('')}</section></main>`}
function docsView(){return `<main><section class="section-title"><h1>Documents & Requirements</h1></section>${Object.entries(EXTRA.requirements).map(([k,a])=>`<section class="paper-card list-card doc"><h2>${k}</h2>${a.map(x=>`<div class="list-row">${x}</div>`).join('')}</section>`).join('')}</main>`}

function render(){const fn={days:dayView,summary:summaryView,schedule:scheduleView,transport:transportView,reservations:reservationsView,budget:budgetView,packing:packingView,docs:docsView}[state.view]||dayView;document.getElementById('app').innerHTML=topbar()+fn()+bottom();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();scrollTo(0,0)});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=+b.dataset.day;render();scrollTo(0,0)});document.querySelectorAll('[data-transit-day]').forEach(b=>b.onclick=()=>{state.transitDay=+b.dataset.transitDay;render();scrollTo(0,0)});document.querySelectorAll('[data-schedule-day]').forEach(b=>b.onclick=()=>{state.scheduleDay=+b.dataset.scheduleDay;render();scrollTo(0,0)});document.querySelectorAll('[data-tick]').forEach(b=>b.onclick=()=>{done[b.dataset.tick]=!done[b.dataset.tick];save();render()});document.querySelectorAll('[data-note]').forEach(t=>t.oninput=()=>{notes[t.dataset.note]=t.value;save()});document.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>{state.pack=b.dataset.pack;render()});document.querySelectorAll('[data-packtick]').forEach(b=>b.onclick=()=>{packDone[b.dataset.packtick]=!packDone[b.dataset.packtick];save();render()})}
render();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');