const M=window.SHioriSheetMirror, X=window.SHioriSheetExtra;
labels.planning='Planning'; labels.pasalubong='Pasalubong';

function modeIcon(line){if(/bus/i.test(line))return'🚌';if(/walk/i.test(line))return'🚶';if(/N’EX|N'EX|JR|Odakyu|Seibu|Metro|Enoden|Line/i.test(line))return'🚆';if(/flight|Cebu/i.test(line))return'✈️';return'➡️'}

transportView=function(){const d=D.days.find(x=>x.day===state.transitDay),rows=M.transport[d.day]||[];return `<main>${dayTabs('transitDay')}${banner(d)}<section class="transport-title"><h1>Transportation Guide</h1><div>${d.title}</div></section><p class="sheet-source-note">Full content from the master Transport Guide sheet — nothing condensed.</p><section class="transport-cards">${rows.map(r=>`<article class="transport-leg"><div class="leg-top"><span class="leg-num">${String(r[0]).padStart(2,'0')}</span><div class="leg-route">${r[2]}</div><span class="leg-icon">${modeIcon(r[3])}</span></div><div class="leg-grid"><div><small>Time</small><strong>${r[1]}</strong></div><div><small>Transport / Line</small><strong>${r[3]}</strong></div><div class="wide"><small>Details</small><span>${r[4]}</span></div><div class="wide note-cell"><small>Notes</small><span>${r[5]}</span></div></div></article>`).join('')}</section><section class="paper-card quick full-quick"><h2>✓ Quick Notes</h2><p>${M.transportQuickNote}</p></section></main>`}

function hmToMins(t){const m=/^(\d{2}):(\d{2})$/.exec(t);return m?+m[1]*60 + +m[2]:0}
function minsTo24(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function minsTo12(n){let h=Math.floor(n/60),m=n%60,ap=h<12?'AM':'PM';let hh=h%12||12;return `${hh}:${String(m).padStart(2,'0')} ${ap}`}
scheduleView=function(){const d=D.days.find(x=>x.day===state.scheduleDay),src=SCHEDULE[d.day]||[],map={};src.forEach(r=>map[r[0]]=r[1]);const slots=[];for(let n=0;n<1440;n+=15){const key=minsTo24(n);slots.push([minsTo12(n),map[key]||''])}return `<main>${dayTabs('scheduleDay')}<section class="section-title"><h1>15-Min Schedule</h1><p class="section-sub">${d.date} • ${d.title}</p></section><div class="schedule-legend"><span>Pink = planned</span><span>White = open / buffer time</span></div><section class="paper-card full-day-schedule"><div class="sched-head"><div>Time</div><div>Plan</div></div>${slots.map(r=>`<div class="sched-row ${r[1]?'occupied':'open-slot'}"><time>${r[0]}</time><div>${r[1]||'<span class="free-label">Open / buffer</span>'}</div></div>`).join('')}</section><p class="schedule-note">This intentionally shows the complete day in 15-minute intervals, including blank periods, so you can see where the itinerary is packed and where you still have breathing room.</p></main>`}

reservationsView=function(){const h=X.reservations[0],rows=X.reservations.slice(1);return `<main><section class="section-title"><h1>Bookings & Tickets</h1><p class="section-sub">Full Reservations sheet</p></section><section class="detail-card-list">${rows.map(r=>`<article class="paper-card detail-sheet-card"><h2>${r[0]}</h2>${r.slice(1).map((v,i)=>`<div class="sheet-field"><small>${h[i+1]}</small><div>${v||'—'}</div></div>`).join('')}</article>`).join('')}</section></main>`}

budgetView=function(){const rows=X.budget.slice(1);return `<main><section class="section-title"><h1>Trip Budget</h1><p class="section-sub">Full Budget sheet • couple</p></section><section class="detail-card-list">${rows.map(r=>`<article class="paper-card budget-full-card"><div class="budget-full-top"><h2>${r[0]}</h2><strong>${r[1]}</strong></div>${r[2]?`<p>${r[2]}</p>`:''}</article>`).join('')}</section></main>`}

packingView=function(){const groups=M.packing;return `<main><section class="section-title"><h1>Packing Checklist</h1><p class="section-sub">Mirrors Cha • Martin • Both • Medicine from the packing sheet</p></section><div class="day-switch">${Object.keys(groups).map(x=>`<button data-pack="${x}" class="${x===state.pack?'active':''}">${x}</button>`).join('')}</div><section class="paper-card list-card">${groups[state.pack].map((x,i)=>{const k=`${state.pack}-${i}`,on=!!packDone[k];return `<div class="list-row pack-row ${on?'done':''}"><button class="check-btn ${on?'on':''}" data-packtick="${k}">${on?'✓':''}</button><b>${x}</b></div>`}).join('')}</section></main>`}

docsView=function(){return `<main><section class="section-title"><h1>Documents & Requirements</h1><p class="section-sub">Requirements for IO and visa sheet</p></section><section class="paper-card list-card doc"><h2>Visa / application</h2>${X.docs.visa.map(r=>`<div class="doc-row"><b>${r[0]}</b><span>${r[1]||'—'}</span></div>`).join('')}</section><section class="paper-card list-card doc"><h2>Immigration / travel</h2>${X.docs.immigration.map(x=>`<div class="list-row">${x}</div>`).join('')}</section></main>`}

function planningView(){return `<main><section class="section-title"><h1>Planning Inbox</h1><p class="section-sub">Full “To add in itinerary” sheet</p></section><section class="detail-card-list">${M.planning.map(r=>`<article class="paper-card planning-card"><h2>${r[0]}</h2>${r[1]?`<p>${r[1]}</p>`:''}</article>`).join('')}</section></main>`}
function pasalubongView(){return `<main><section class="section-title"><h1>Pasalubong List</h1><p class="section-sub">Mirrors the hidden Pasalubong sheet</p></section>${Object.entries(M.pasalubong).map(([g,rows])=>`<section class="paper-card gift-group"><h2>${g}</h2>${rows.map(r=>`<div class="gift-row"><b>${r[0]}</b><span>${r[1]}</span></div>`).join('')}</section>`).join('')}</main>`}

render=function(){const fn={days:dayView,summary:summaryView,schedule:scheduleView,transport:transportView,reservations:reservationsView,budget:budgetView,packing:packingView,docs:docsView,planning:planningView,pasalubong:pasalubongView}[state.view]||dayView;document.getElementById('app').innerHTML=topbar()+fn()+bottom();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();scrollTo(0,0)});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=+b.dataset.day;render();scrollTo(0,0)});document.querySelectorAll('[data-transit-day]').forEach(b=>b.onclick=()=>{state.transitDay=+b.dataset.transitDay;render();scrollTo(0,0)});document.querySelectorAll('[data-schedule-day]').forEach(b=>b.onclick=()=>{state.scheduleDay=+b.dataset.scheduleDay;render();scrollTo(0,0)});document.querySelectorAll('[data-tick]').forEach(b=>b.onclick=()=>{done[b.dataset.tick]=!done[b.dataset.tick];save();render()});document.querySelectorAll('[data-note]').forEach(t=>t.oninput=()=>{notes[t.dataset.note]=t.value;save()});document.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>{state.pack=b.dataset.pack;render()});document.querySelectorAll('[data-packtick]').forEach(b=>b.onclick=()=>{packDone[b.dataset.packtick]=!packDone[b.dataset.packtick];save();render()})};
render();